import type { CanvasCardRecord, ChatMessage, ConversationThread, PendingItem, RailItem } from './types';

export const railItems: RailItem[] = [
  {
    id: 'manager-1',
    section: 'manager',
    title: '总经理汇报',
    summary: '已拆解 2 个项目，wanman.ai iOS App 已完成设计输出，当前有 2 个关键事项等待 CEO 确认。',
    statusLabel: '2 项待你确认',
    count: 2,
    targetCardId: 'report-1',
  },
  {
    id: 'dept-1',
    section: 'departments',
    title: '设计部',
    summary: '首页方向与 spec 已提交，等待汇总批示。',
    statusLabel: '进行中',
    targetCardId: 'task-1',
  },
  {
    id: 'dept-2',
    section: 'departments',
    title: '开发部',
    summary: '等待设计方向锁定后进入编码。',
    statusLabel: '待输入',
    targetCardId: 'task-2',
  },
  {
    id: 'archive-1',
    section: 'archive',
    title: '历史归档',
    summary: '上周完成 4 个事项，可随时回看。',
    statusLabel: '4 条记录',
    count: 4,
    targetCardId: 'project-1',
  },
];

export const conversationThreads: ConversationThread[] = [
  {
    id: 'thread-manager',
    title: 'CEO 和总经理的聊天',
    kind: 'manager',
    lastMessage: '设计阶段已经收拢，我建议你确认后直接进入开发。',
    statusLabel: '2 项待确认',
    unreadCount: 2,
  },
  {
    id: 'thread-design',
    title: 'CEO 和设计部的聊天',
    kind: 'department',
    department: 'design',
    lastMessage: '三套首页方向与 spec 已提交，可以继续追问细节。',
    statusLabel: '已提交',
  },
  {
    id: 'thread-engineering',
    title: 'CEO 和开发部的聊天',
    kind: 'department',
    department: 'engineering',
    lastMessage: '当前等待设计方向锁定，开发未开始编码。',
    statusLabel: '阻塞',
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'message-1',
    threadId: 'thread-manager',
    author: 'CEO',
    body: '帮我给 wanman.ai 做一版新的 iOS App，先把设计方向和是否进入开发跑清楚。',
    side: 'right',
  },
  {
    id: 'message-2',
    threadId: 'thread-manager',
    author: '总经理',
    body: '我已经拉起设计部完成第一轮探索，并把需要你拍板的节点整理成单独卡片。',
    side: 'left',
    linkedCardId: 'report-1',
  },
  {
    id: 'message-3',
    threadId: 'thread-manager',
    author: '总经理',
    body: '设计阶段已经收拢，我建议你确认推荐方向后直接进入开发。',
    side: 'left',
    linkedCardId: 'approval-1',
  },
  {
    id: 'message-4',
    threadId: 'thread-design',
    author: '设计部',
    body: '我们已经提交 3 套首页方向，并补完了 spec，当前等待你或总经理确认推荐稿。',
    side: 'left',
    linkedCardId: 'task-1',
  },
  {
    id: 'message-5',
    threadId: 'thread-design',
    author: 'CEO',
    body: '我想看推荐稿为什么更适合做第一版，请把取舍直接讲清楚。',
    side: 'right',
  },
  {
    id: 'message-6',
    threadId: 'thread-engineering',
    author: '开发部',
    body: '当前等待设计方向锁定，开发未开始编码；骨架和状态管理方案已经准备好。',
    side: 'left',
    linkedCardId: 'task-2',
  },
];

export const canvasCards: CanvasCardRecord[] = [
  {
    id: 'project-1',
    lane: 'ceo',
    type: 'project',
    title: 'wanman.ai 新 iOS App 设计与启动',
    summary: 'CEO 要求总经理组织一版完整的 iOS 设计方案，并在进入开发前完成关键确认。',
    owner: 'CEO',
    status: 'active',
    updatedAt: '5m ago',
    tags: ['P0', 'watch'],
    projectId: 'wanman',
  },
  {
    id: 'report-1',
    lane: 'manager',
    type: 'report',
    title: '总经理阶段汇报',
    summary: '已完成设计探索与 spec 草稿，建议先确认推荐方向再进入开发。',
    owner: '总经理',
    status: 'awaiting_ceo',
    updatedAt: '3m ago',
    tags: ['汇报', '建议'],
    projectId: 'wanman',
  },
  {
    id: 'task-1',
    lane: 'design',
    type: 'task',
    title: '输出 3 套首页设计方向',
    summary: '覆盖完整首页信息层级，并附推荐方案与取舍说明。',
    owner: '设计部',
    status: 'submitted',
    updatedAt: '12m ago',
    tags: ['设计', '首页'],
    projectId: 'wanman',
  },
  {
    id: 'deliverable-1',
    lane: 'design',
    type: 'deliverable',
    title: 'wanman-ios-app-design-spec.md',
    summary: '设计稿与 spec 已提交，包含推荐视觉方向与页面覆盖清单。',
    owner: 'Designer',
    status: 'ready',
    updatedAt: '9m ago',
    tags: ['交付物', 'Spec'],
    projectId: 'wanman',
  },
  {
    id: 'approval-1',
    lane: 'decisions',
    type: 'approval',
    title: '是否按推荐方案进入开发',
    summary: '若不确认，开发部门将暂停等待，当前建议按方案 B 推进。',
    owner: 'CEO',
    status: 'pending',
    updatedAt: '2m ago',
    tags: ['Heavy', '待审批'],
    projectId: 'wanman',
  },
  {
    id: 'task-2',
    lane: 'engineering',
    type: 'task',
    title: '准备开发启动骨架',
    summary: '在方向锁定后接手结构搭建、状态管理和组件实现。',
    owner: '开发部',
    status: 'blocked',
    updatedAt: '1m ago',
    tags: ['阻塞', '等待设计确认'],
    projectId: 'wanman',
  },
];

export const mockPendingItems: PendingItem[] = [
  {
    id: 'pending-w1',
    projectId: 'wanman',
    projectName: 'wanman.ai iOS App',
    projectPriority: 'P0',
    title: '是否按推荐方案进入开发',
    itemType: 'approval',
    severity: 'heavy',
    recommendation: '按方案 B 推进，返工风险最低。',
    impact: '如果不处理，开发将暂停等待。',
  },
  {
    id: 'pending-w2',
    projectId: 'wanman',
    projectName: 'wanman.ai iOS App',
    projectPriority: 'P0',
    title: '首页视觉方向是否锁定为推荐稿',
    itemType: 'confirmation',
    severity: 'medium',
    recommendation: '锁定推荐稿，其余方向留作后续迭代参考。',
    impact: '如果不处理，设计与开发会继续摇摆。',
  },
  {
    id: 'pending-b1',
    projectId: 'brand-refresh',
    projectName: 'Brand Refresh',
    projectPriority: 'P1',
    title: '设计改稿可能影响两天排期',
    itemType: 'risk',
    severity: 'medium',
    recommendation: '先锁品牌首页，再延后次级页面。',
    impact: '如果继续扩展范围，项目交付会顺延。',
  },
];
