import type {
  CanvasCardRecord,
  ChatMessage,
  ConversationThread,
  PendingItem,
  RailItem,
  StageLayer,
  TeamDepartment,
} from './types';

export const railItems: RailItem[] = [
  {
    id: 'manager-1',
    section: 'manager',
    title: '总经理汇报',
    summary: '已拆解 2 个项目，wanman.ai iOS App 已完成设计输出，当前有 2 个关键事项等待 CEO 确认。',
    statusLabel: '2 项待你确认',
    count: 2,
    targetCardId: 'report-1',
  },
  {
    id: 'dept-1',
    section: 'departments',
    title: '设计部',
    summary: '首页方向与 spec 已提交，等待汇总批示。',
    statusLabel: '进行中',
    targetCardId: 'task-1',
  },
  {
    id: 'dept-2',
    section: 'departments',
    title: '开发部',
    summary: '等待设计方向锁定后进入编码。',
    statusLabel: '待输入',
    targetCardId: 'task-2',
  },
  {
    id: 'archive-1',
    section: 'archive',
    title: '历史归档',
    summary: '上周完成 4 个事项，可随时回看。',
    statusLabel: '4 条记录',
    count: 4,
    targetCardId: 'project-1',
  },
];

export const conversationThreads: ConversationThread[] = [
  {
    id: 'thread-manager',
    title: 'CEO 和总经理的聊天',
    kind: 'manager',
    lastMessage: '设计阶段已经收拢，我建议你确认后直接进入开发。',
    statusLabel: '2 项待确认',
    unreadCount: 2,
  },
  {
    id: 'thread-design',
    title: 'CEO 和设计部的聊天',
    kind: 'department',
    department: 'design',
    lastMessage: '三套首页方向与 spec 已提交，可以继续追问细节。',
    statusLabel: '已提交',
  },
  {
    id: 'thread-engineering',
    title: 'CEO 和开发部的聊天',
    kind: 'department',
    department: 'engineering',
    lastMessage: '当前等待设计方向锁定，开发未开始编码。',
    statusLabel: '阻塞',
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'message-1',
    threadId: 'thread-manager',
    author: 'CEO',
    body: '帮我给 wanman.ai 做一版新的 iOS App，先把设计方向和是否进入开发跑清楚。',
    side: 'right',
  },
  {
    id: 'message-2',
    threadId: 'thread-manager',
    author: '总经理',
    body: '我已经拉起设计部完成第一轮探索，并把需要你拍板的节点整理成单独卡片。',
    side: 'left',
    linkedCardId: 'report-1',
  },
  {
    id: 'message-3',
    threadId: 'thread-manager',
    author: '总经理',
    body: '设计阶段已经收拢，我建议你确认推荐方向后直接进入开发。',
    side: 'left',
    linkedCardId: 'approval-1',
  },
  {
    id: 'message-4',
    threadId: 'thread-design',
    author: '设计部',
    body: '我们已经提交 3 套首页方向，并补完了 spec，当前等待你或总经理确认推荐稿。',
    side: 'left',
    linkedCardId: 'task-1',
  },
  {
    id: 'message-5',
    threadId: 'thread-design',
    author: 'CEO',
    body: '我想看推荐稿为什么更适合做第一版，请把取舍直接讲清楚。',
    side: 'right',
  },
  {
    id: 'message-6',
    threadId: 'thread-engineering',
    author: '开发部',
    body: '当前等待设计方向锁定，开发未开始编码；骨架和状态管理方案已经准备好。',
    side: 'left',
    linkedCardId: 'task-2',
  },
];

export const teamDepartments: TeamDepartment[] = [
  {
    id: 'dept-ceo-office',
    name: 'CEO办公室',
    summary: '当前真实存在的核心管理层。',
    agents: [{ id: 'agent-manager', name: '总经理', title: '公司总经理 agent' }],
  },
  {
    id: 'dept-design',
    name: '设计部',
    summary: '总经理已创建的设计团队成员。',
    agents: [
      { id: 'agent-illustration', name: '原画设计' },
      { id: 'agent-modeling', name: '模型设计' },
      { id: 'agent-scene', name: '场景设计' },
    ],
  },
  {
    id: 'dept-engineering',
    name: '开发部',
    summary: '总经理已创建的开发团队成员。',
    agents: [
      { id: 'agent-frontend', name: '前端开发' },
      { id: 'agent-client', name: '客户端开发' },
    ],
  },
];

export const stageLayers: StageLayer[] = [
  {
    id: 'ceo',
    label: 'CEO层',
    description: 'CEO 视角下的本轮推进总览与部门汇总。',
    cards: [
      {
        id: 'ceo-progress',
        title: '本轮工作进度',
        body: '当前这一轮工作已经完成部门协同与阶段汇总，CEO 可以直接看到设计、开发两侧的推进状态与下一步重点。',
        owner: '总经理',
        updatedAt: '3m ago',
        statusLabel: '本轮汇总',
        artifactLabels: ['工作进度', '中心舞台'],
        position: { x: 48, y: 48, w: 640 },
        tone: 'accent',
      },
      {
        id: 'ceo-design-summary',
        title: '设计部总结',
        body: '设计部已完成本轮方向探索、推荐方案与 spec 归拢，当前重点是等待确认后进入定稿和交付同步。',
        owner: '设计部',
        updatedAt: '2m ago',
        statusLabel: '部门总结',
        artifactLabels: ['设计方向', 'Spec 汇总'],
        position: { x: 736, y: 136, w: 384 },
        rotation: -2,
        tone: 'paper',
      },
      {
        id: 'ceo-engineering-summary',
        title: '开发部总结',
        body: '开发部已准备好启动骨架与状态方案，当前按管理节奏维持待命，确认后即可接续设计结果进入实现。',
        owner: '开发部',
        updatedAt: '1m ago',
        statusLabel: '部门总结',
        artifactLabels: ['启动骨架', '待进入实现'],
        position: { x: 736, y: 360, w: 384 },
        rotation: 1,
        tone: 'paper',
      },
    ],
    connections: [
      {
        id: 'ceo-progress-to-design-summary',
        from: 'ceo-progress',
        to: 'ceo-design-summary',
        label: '设计汇总',
      },
      {
        id: 'ceo-progress-to-engineering-summary',
        from: 'ceo-progress',
        to: 'ceo-engineering-summary',
        label: '开发汇总',
      },
    ],
  },
  {
    id: 'design',
    label: '设计部',
    description: '设计团队内部进度与交接开发的内容。',
    cards: [
      {
        id: 'design-progress',
        title: '设计部内部进度',
        body: '首页推荐方向、组件清单和页面级 spec 已在设计部内部对齐完成，当前只剩最终定稿前的细节核对。',
        owner: '设计部',
        updatedAt: '8m ago',
        statusLabel: '内部推进',
        artifactLabels: ['推荐方向', 'Spec 对齐'],
        position: { x: 48, y: 48, w: 620 },
        tone: 'paper',
      },
      {
        id: 'design-feedback',
        title: '交给开发的内容',
        body: '一旦 CEO 确认推荐稿，设计部会把切图、交互动效说明、组件标注和页面状态说明一起交接给开发部。',
        owner: '设计负责人',
        updatedAt: '5m ago',
        statusLabel: '待交接',
        artifactLabels: ['切图资源', '交互标注'],
        position: { x: 724, y: 152, w: 396 },
        rotation: 1,
        tone: 'accent',
      },
    ],
    connections: [
      {
        id: 'design-progress-to-feedback',
        from: 'design-progress',
        to: 'design-feedback',
        label: '等待定稿',
      },
    ],
  },
  {
    id: 'engineering',
    label: '开发部',
    description: '开发团队内部进度与当前阻塞依赖。',
    cards: [
      {
        id: 'engineering-progress',
        title: '开发部内部进度',
        body: '项目骨架、状态管理方案和关键页面容器已经在开发部内部准备完成，收到最终设计后即可直接进入实现。',
        owner: '开发部',
        updatedAt: '4m ago',
        statusLabel: '内部推进',
        artifactLabels: ['项目骨架', '状态方案'],
        position: { x: 48, y: 48, w: 620 },
        tone: 'paper',
      },
      {
        id: 'engineering-blocker',
        title: '等待设计最终确认',
        body: '视觉稿、交互动效和页面状态说明还要等设计部最终确认后才能冻结，所以开发当前只能等待这一外部依赖。',
        owner: '前端负责人',
        updatedAt: '1m ago',
        statusLabel: '阻塞',
        artifactLabels: ['等待设计确认'],
        position: { x: 732, y: 128, w: 388 },
        rotation: -1,
        tone: 'warning',
      },
    ],
    connections: [
      {
        id: 'engineering-progress-to-blocker',
        from: 'engineering-progress',
        to: 'engineering-blocker',
        label: '受设计影响',
      },
    ],
  },
];

export const canvasCards: CanvasCardRecord[] = [
  {
    id: 'project-1',
    lane: 'ceo',
    type: 'project',
    title: 'wanman.ai 新 iOS App 设计与启动',
    summary: 'CEO 要求总经理组织一版完整的 iOS 设计方案，并在进入开发前完成关键确认。',
    owner: 'CEO',
    status: 'active',
    updatedAt: '5m ago',
    tags: ['P0', 'watch'],
    projectId: 'wanman',
  },
  {
    id: 'report-1',
    lane: 'manager',
    type: 'report',
    title: '总经理阶段汇报',
    summary: '已完成设计探索与 spec 草稿，建议先确认推荐方向再进入开发。',
    owner: '总经理',
    status: 'awaiting_ceo',
    updatedAt: '3m ago',
    tags: ['汇报', '建议'],
    projectId: 'wanman',
  },
  {
    id: 'task-1',
    lane: 'design',
    type: 'task',
    title: '输出 3 套首页设计方向',
    summary: '覆盖完整首页信息层级，并附推荐方案与取舍说明。',
    owner: '设计部',
    status: 'submitted',
    updatedAt: '12m ago',
    tags: ['设计', '首页'],
    projectId: 'wanman',
  },
  {
    id: 'deliverable-1',
    lane: 'design',
    type: 'deliverable',
    title: 'wanman-ios-app-design-spec.md',
    summary: '设计稿与 spec 已提交，包含推荐视觉方向与页面覆盖清单。',
    owner: 'Designer',
    status: 'ready',
    updatedAt: '9m ago',
    tags: ['交付物', 'Spec'],
    projectId: 'wanman',
  },
  {
    id: 'approval-1',
    lane: 'decisions',
    type: 'approval',
    title: '是否按推荐方案进入开发',
    summary: '若不确认，开发部门将暂停等待，当前建议按方案 B 推进。',
    owner: 'CEO',
    status: 'pending',
    updatedAt: '2m ago',
    tags: ['Heavy', '待审批'],
    projectId: 'wanman',
  },
  {
    id: 'task-2',
    lane: 'engineering',
    type: 'task',
    title: '准备开发启动骨架',
    summary: '在方向锁定后接手结构搭建、状态管理和组件实现。',
    owner: '开发部',
    status: 'blocked',
    updatedAt: '1m ago',
    tags: ['阻塞', '等待设计确认'],
    projectId: 'wanman',
  },
];

export const mockPendingItems: PendingItem[] = [
  {
    id: 'pending-w1',
    projectId: 'wanman',
    projectName: 'wanman.ai iOS App',
    projectPriority: 'P0',
    title: '是否按推荐方案进入开发',
    itemType: 'approval',
    severity: 'heavy',
    recommendation: '按方案 B 推进，返工风险最低。',
    impact: '如果不处理，开发将暂停等待。',
  },
  {
    id: 'pending-w2',
    projectId: 'wanman',
    projectName: 'wanman.ai iOS App',
    projectPriority: 'P0',
    title: '首页视觉方向是否锁定为推荐稿',
    itemType: 'confirmation',
    severity: 'medium',
    recommendation: '锁定推荐稿，其余方向留作后续迭代参考。',
    impact: '如果不处理，设计与开发会继续摇摆。',
  },
  {
    id: 'pending-b1',
    projectId: 'brand-refresh',
    projectName: 'Brand Refresh',
    projectPriority: 'P1',
    title: '设计改稿可能影响两天排期',
    itemType: 'risk',
    severity: 'medium',
    recommendation: '先锁品牌首页，再延后次级页面。',
    impact: '如果继续扩展范围，项目交付会顺延。',
  },
];
